CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY 'siame1234';
CREATE USER IF NOT EXISTS 'admin'@'127.0.0.1' IDENTIFIED BY 'siame1234';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
ON service_management_db.* TO 'admin'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES
ON service_management_db.* TO 'admin'@'127.0.0.1';

FLUSH PRIVILEGES;
